services:
  - type: web
    name: tms-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: |
      python manage.py migrate --noinput && gunicorn tms.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: django-insecure-0(9xs(zofr6@+obruwgvq9c4vt72u*ovju^7z8__bpzdyzhan-
      - key: DATABASE_URL
        fromDatabase:
          name: tms-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: daramolaponmilee@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: sxbsocluzavninhz

databases:
  - name: tms-db
    databaseName: tms_db
    user: tms_user
