# Generated by Django 5.1.7 on 2025-03-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
