# Generated by Django 5.1.7 on 2025-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_project_link_task_updated_at_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('DEVELOPER', 'Developer')], max_length=20),
        ),
    ]
