# Generated by Django 5.1.7 on 2025-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Developer', 'Developer')], max_length=20),
        ),
    ]
