# Generated by Django 5.1.7 on 2025-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='text',
        ),
    ]
