# Generated by Django 5.1.7 on 2025-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_timestamp_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('Task Created', 'Task Created'), ('Status Updated', 'Status Updated'), ('Comment Added', 'Comment Added')], max_length=50),
        ),
    ]
