# Generated by Django 5.1.7 on 2025-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_activitylog_options_activitylog_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
