# Generated by Django 5.1.7 on 2025-03-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
